# Timeout in seconds that Limine will use before automatically booting.
timeout: 3

# The entry name that will be displayed in the boot menu.
/AxeniaOS
    # We use the Limine boot protocol.
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/kernel

/AxeniaOS (Linux Protocol)
    # We use the Linux boot protocol.
    protocol: linux

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/kernel